#!/usr/bin/env node

var gaze = require('gaze');
var colors = require('colors');
var path = require('path');
var spawn = require('child_process').spawn;

var APP_ROOT = path.join(__dirname, '..');
var JS_EXT = path.join('**', '*.js');

var dirs = [
  path.join(APP_ROOT, 'src', JS_EXT),
  path.join(APP_ROOT, 'test', JS_EXT),
  path.join(APP_ROOT, 'data', JS_EXT),
  path.join(APP_ROOT, 'webpack', JS_EXT),
];

function lint() {
  var linter = spawn('./scripts/lint', [], {stdio: 'inherit'});

  if (linter.stdout) {
    linter.stdout.on('data', function(data) {
      process.stdout.write(data);
    });
  }

  if (linter.stderr) {
    linter.stderr.on('data', function(data) {
      process.stderr.write(data);
    });
  }

  linter.on('exit', function(code) {
    if (code === 0) {
      process.stdout.write(colors.green('✓ 0 problems (0 errors, 0 warnings)\n'));
    }
  });
}

gaze(dirs, function(filepath) {
  this.on('all', function(event, filepath) {
    lint();
  });

  lint();
});
