#!/usr/bin/env node_modules/.bin/babel-node --stage=0

import fs from 'fs';
import path from 'path';
import {graphql} from 'graphql';
import {introspectionQuery} from 'graphql/utilities';
import Schema from '../data/schema';

(async () => {
  const result = await graphql(Schema, introspectionQuery);

  if (result.errors) {
    console.error('ERROR: ', JSON.stringify(result.errors, null, 2));
  } else {
    fs.writeFileSync(
      path.join(__dirname, '..', 'build', 'schema.json'),
      JSON.stringify(result, null, 2)
    );
  }
})();
